Kredek_C#/lab05/KlaudiaGoraLab5/Controllers/EmployeeController.cs
using KlaudiaGoraLab5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KlaudiaGoraLab5.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Emplyee
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            List<Employee> employee;

            using (var ctx = new PizzaContext())
            {

                employee = ctx.Employees.ToList();
            }
            return View(employee);
        }

        public ActionResult Add()
        {
            return View(new Employee());
        }

        [HttpPost]
        public ActionResult Add(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return View(new Employee());
            }
            using (var ctx = new PizzaContext())
            {
                ctx.Employees.Add(employee);
                ctx.SaveChanges();
            }

            return RedirectToAction("List");
        }


        public ActionResult Edit(int id)
        {
            Employee employee;
            using (var ctx = new PizzaContext())
            {
                employee = ctx.Employees.FirstOrDefault(p => p.Id == id);
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit(Employee model, int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit");
            }
            Employee employee;
            using (var ctx = new PizzaContext())
            {
                employee = ctx.Employees.FirstOrDefault(p => p.Id == id);
                employee.Name = model.Name;
                employee.Surname = model.Surname;
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public ActionResult Remove(int id)
        {
            Employee employee;
            using (var ctx = new PizzaContext())
            {
                employee = ctx.Employees.FirstOrDefault(p => p.Id == id);
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult Remove(Employee model, int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Remove");
            }
            Employee employee;
            using (var ctx = new PizzaContext())
            {
                employee = ctx.Employees.FirstOrDefault(p => p.Id == id);
                //pizza.Name = model.Name;
                //pizza.Ingredients = model.Ingredients;
                ctx.Employees.Remove(employee);
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

Kredek_C#/lab05/KlaudiaGoraLab5/Controllers/PizzaController.cs
using KlaudiaGoraLab5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KlaudiaGoraLab5.Controllers
{
    public class PizzaController : Controller
    {
        // GET: Pizza
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            List<Pizza> pizzas;

            using (var ctx = new PizzaContext())
            {

               pizzas = ctx.Danie.ToList();
            }
            return View(pizzas);
        }

        public ActionResult Add()
        {
            return View(new Pizza());
        }

        [HttpPost]
        public ActionResult Add(Pizza pizza)
        {
            if (!ModelState.IsValid)
            {
                return View(new Pizza());
            }
            using (var ctx = new PizzaContext())
            {
                ctx.Danie.Add(pizza);
                ctx.SaveChanges();
            }

            return RedirectToAction("List");
        }


        public ActionResult Edit(int id)
        {
            Pizza pizza;
            using (var ctx = new PizzaContext())
            {
                pizza = ctx.Danie.FirstOrDefault(p => p.Id == id);
            }
            return View(pizza);
        }

        [HttpPost]
        public ActionResult Edit(Pizza model, int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit");
            }
            Pizza pizza;
            using (var ctx = new PizzaContext())
            {
                pizza = ctx.Danie.FirstOrDefault(p => p.Id == id);
                pizza.Name = model.Name;
                pizza.Ingredients = model.Ingredients;
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
        [HttpPost]
        public ActionResult Remove(Pizza model, int id)
        {
            using (var ctx = new PizzaContext())
            {
                var pizza = ctx.Danie.SingleOrDefault(p => p.Id == id);
                ctx.Danie.Remove(pizza);
                ctx.SaveChanges();
            }

            return RedirectToAction("List");
        }
    }

       
  
}

Kredek_C#/lab05/KlaudiaGoraLab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<link rel="Shortcut icon" href="https://www.clipartsgram.com/image/1968095208-pizza2001.gif" />

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pizzeria", "Start", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Menu", "List", "Pizza")</li>
                    <li>@Html.ActionLink("Pracownicy", "List", "Employee")</li>
                    <li>@Html.ActionLink("Post", "List", "Post")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — moja aplikacja platformy ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>